name: Build and deploy to QA

on:
  push:
    branches:
      - "qa"
      - "main"

env:
  SERVER_PROJECT_NAME: powerimo-short-links-server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Set up Docker Buildx
      if: github.ref == 'refs/heads/qa'
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/qa'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/qa'
      uses: docker/build-push-action@v3
      with:
        context: ./${{ env.SERVER_PROJECT_NAME }}/
        push: true
        tags: |
          powerimo/${{ env.SERVER_PROJECT_NAME }}:qa

    - name: Logout from Docker Hub
      if: github.ref == 'refs/heads/qa'
      run: docker logout

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/qa'
    environment:
      name: qa

    steps:
      - name: Checkout scripts
        uses: actions/checkout@v4
      - name: Copy script to SSH server
        uses: nicklasfrahm/scp-action@main
        with:
          direction: upload
          host: ${{ secrets.SSH_HOST }}
          fingerprint: ${{ vars.SSH_FINGERPRINT }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_USER_KEY }}
          source: cicd/bash/deploy-server.sh
          target: ~/bin/deploy-${{ env.SERVER_PROJECT_NAME }}.sh
      - name: Deploy to QA
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_USER_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod +x ~/bin/deploy-${{ env.SERVER_PROJECT_NAME }}.sh
            ~/bin/deploy-${{ env.SERVER_PROJECT_NAME }}.sh "${{ env.SERVER_PROJECT_NAME }}-qa" "powerimo/${{ env.SERVER_PROJECT_NAME }}:qa" "qa"
